### ISSUE TITLE
Error creatinmg races on launch

### ISSUE THREAD

**Issue by suppoo** [Firewolf1337/RCRPlanner#2]
Hey, is still still maintained?

Getting following error on launch

"Error creating races: String was not recognized as valid DateTime."

**Comment by Firewolf1337** [comment]
Hi,
can you zip all the .xml files in the static folder and upload them here? So I can check what the problem is with the data.

**Comment by suppoo** [comment]
[static.zip](https://github.com/Firewolf1337/RCRPlanner/files/14068397/static.zip)
Hey, thanks for quick reply! Heres all the xml files

**Comment by Firewolf1337** [comment]
Hmm thats strange the data is correct. 
What Windows version , language and regional format do you have.

**Comment by suppoo** [comment]
Windows 11, English and regional formats are Finnish. Windows time for example is displayed with single dot (22.43) as example. Could this be the issue?

**Comment by Firewolf1337** [comment]
I've changed my setting to englisch (US) and Finnish formats but i don't get that error. Is this the only error you get? So the rest of the app is working? The only other idea i have is that there is something not ok in the user.xml which is in the main folder. Can you upload it also but _**remove your personal information first**_ 
If so I would create a debuggin version for you where it should tell me at which exact point it is failing. 

If the rest is also not working I would kindly ask you to install MS Visual Studio and download the project and start the debugging on your maschine. If you are willing to do that I will assist you.

**Comment by Firewolf1337** [comment]
[Debug.zip](https://github.com/Firewolf1337/RCRPlanner/files/14071858/Debug.zip)
This should give me some more information where it happens. Just copy the two files in the zip to the programm folder and replace the existing files.

**Comment by suppoo** [comment]
Hey, I just tried to change my clock format to use ":" as seperator instead of "." and it seemed to have fixed it. I'll run debug version asap.

Other than that application worked great. Only that error at start and upcoming races were not loading.
Thanks for all the help and I'll report back soon!

**Comment by Firewolf1337** [comment]
Glad to here that you could "fix" it by yourself. 
If you can reproduce that error with the debugging version it would be great to get the screenshot of the message. But it could be possible that I already fixed it in the debugging version :D
I didn't know that there is a region where time is also separated by a dot like a date. 

Hope you enjoy using the planner and if you have any features you would like to see just create a new issue.
